import path from "path"
import { extractFile, walkSourceFiles, TFileDoc } from "./extract"
import { writeIfChanged } from "./write-if-changed"

/**
 * Gera o `src/index.ts` a partir da extração puramente sintática de `scripts/doc/extract.ts`
 * — sem o compiler API do TypeScript.
 *
 * Regras:
 * - Arquivo com efeito colateral (`declare global`/`declare module` ou `@required`) entra
 *   como `import './arquivo'`, sem re-exportar nada.
 * - Símbolo `@internal` não entra.
 * - `class`/`function`/`const`/`let`/`var`/`enum` → re-export de runtime; `type`/`interface`
 *   → `export type`. Um nome com as duas formas no mesmo arquivo (ex: `type X` + `const X`)
 *   conta como runtime.
 */

const HEADER = "// Generated by scripts/doc/index-gen.ts"

const RUNTIME_KINDS = new Set(["class", "function", "const", "let", "var", "enum"])

function isInternal(decl: TFileDoc["declarations"][number]): boolean {
	return decl.doc?.tags.some((tag) => tag.name === "internal") ?? false
}

/** `src/mask/token/model.ts` + entryDir `src` → `./mask/token/model` */
function importSpecifier(filePath: string, entryDir: string): string {
	const rel = path.relative(entryDir, filePath).replace(/\\/g, "/").replace(/\.tsx?$/, "")
	return `./${rel}`
}

/** Monta o conteúdo do index (string, sem newline final) a partir dos arquivos já extraídos. */
function buildIndex(files: TFileDoc[], entryDir: string, entryPath: string): string {
	const imports: string[] = []
	const runtimeExports: string[] = []
	const typeExports: string[] = []

	for (const file of files) {
		if (file.path === entryPath) continue
		const spec = importSpecifier(file.path, entryDir)

		if (file.sideEffect) {
			imports.push(`import '${spec}'`)
			continue
		}

		// Agrupa por nome exportado: um nome com qualquer declaração de runtime é runtime.
		const runtime = new Set<string>()
		const types = new Set<string>()
		const seen: string[] = []
		for (const decl of file.declarations) {
			if (!decl.exported || isInternal(decl)) continue
			if (!runtime.has(decl.name) && !types.has(decl.name)) seen.push(decl.name)
			if (RUNTIME_KINDS.has(decl.kind)) {
				runtime.add(decl.name)
				types.delete(decl.name)
			} else if (!runtime.has(decl.name)) {
				types.add(decl.name)
			}
		}

		// Ordem: a das cláusulas `export { … }`; nomes só com `export` inline vão no fim,
		// em ordem de declaração.
		const ordered = [
			...file.exportOrder.filter((name) => runtime.has(name) || types.has(name)),
			...seen.filter((name) => !file.exportOrder.includes(name)),
		]
		const runtimeNames = ordered.filter((name) => runtime.has(name))
		const typeNames = ordered.filter((name) => types.has(name))

		if (runtimeNames.length) runtimeExports.push(`export { ${runtimeNames.join(", ")} } from '${spec}'`)
		if (typeNames.length) typeExports.push(`export type { ${typeNames.join(", ")} } from '${spec}'`)
	}

	return [
		HEADER,
		"// #region Required Runtime Code",
		...imports,
		"\n// #region Runtime Code",
		...runtimeExports,
		"\n// #region Typings",
		...typeExports,
	].join("\n")
}

/**
 * Varre `<projectDir>/src`, extrai cada arquivo e (re)escreve o entry só se o conteúdo
 * mudou. `entry` é o caminho do index relativo a `projectDir` (default `src/index.ts`).
 */
function writeIndex(projectDir: string, entry = "src/index.ts"): boolean {
	const srcDir = path.join(projectDir, "src")
	const entryDir = path.dirname(entry).replace(/\\/g, "/")
	const files = walkSourceFiles(srcDir).map((abs) =>
		extractFile(abs, path.relative(projectDir, abs).replace(/\\/g, "/")),
	)
	const content = buildIndex(files, entryDir, entry.replace(/\\/g, "/"))
	return writeIfChanged(path.join(projectDir, entry), content)
}

export {
	buildIndex,
	writeIndex,
}

if (process.argv[1]?.endsWith("index-gen.ts")) {
	const entry = process.argv[2] || "src/index.ts"
	const changed = writeIndex(process.cwd(), entry)
	console.log(`${changed ? "wrote" : "unchanged"} ${entry}`)
}
