import path from "path";
import { AnalyzerProject } from "../analyzer/model";
import { logger } from "../logger";

export function isTestFile(file: { relativePath: string }): boolean {
	return /\.test\.(ts|tsx)$/.test(file.relativePath);
}

export function createEntryFile(project: AnalyzerProject, entry: string) {
	const basePath = path.dirname(entry);
	const importsFiles: string[] = [];
	const exportsFiles: string[] = [];
	const exportsTypes: string[] = [];

	logger.info(`Generating index at ${entry}`);

	project.files.forEach((file) => {
		if (file.relativePath === entry) return;
		if (isTestFile(file)) return;
		const relativePath = path.relative(basePath, file.relativePath).replace(file.ext, "");

		const hasGlobalContext = file.blocks.some((b) => b.context === "global");
		const hasModuleContext = file.blocks.some((b) => b.context === "module");
		const hasRequired = file.standaloneComments.some((c) => c?.text.includes("@required"));

		if (hasGlobalContext || hasModuleContext || hasRequired) {
			importsFiles.push(`import './${relativePath}'`);
			return;
		}

		if (!file.exports.length) return;

		const typeExports: string[] = [];
		const runtimeExports: string[] = [];

		file.exports.forEach((exp) => {
			const {blockCode} = exp

			if (blockCode.isInternal()) return;
			if (blockCode.isTypeOnly) {
				typeExports.push(exp.name);
			} else {
				runtimeExports.push(exp.name);
			}
		})

		if (typeExports.length) {
			exportsTypes.push(`export type { ${typeExports.join(", ")} } from './${relativePath}'`)
		}
		if (runtimeExports.length) {
			exportsFiles.push(`export { ${runtimeExports.join(", ")} } from './${relativePath}'`)
		}
	})

	project.writeFile(entry, [
		'// Generated by scripts/tools/index-generator.ts',
		'// #region Required Runtime Code',
		...importsFiles,
		'\n// #region Runtime Code',
		...exportsFiles,
		'\n// #region Typings',
		...exportsTypes
	].join("\n"))
}
